/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.GestionAlquiler;
import Controladores.GestionPistas;
import Controladores.UtilidadesPantalla;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelos.Alquiler;
import Modelos.Pista;
import Modelos.Usuario;
import java.util.ArrayList;
import javax.help.HelpBroker;
import javax.help.HelpSet;

/**
 *
 * @author DAM2
 */
public class ReservarPista extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ReservarPista(Usuario usu) {
        this.usuarioReservar = usu;
        initComponents();
        rellenarTablas();
        //iniciarOtrosComponentes();
        ponLaAyuda();
        UtilidadesPantalla.resolucionPantalla(this);
        GA.cargarHorasDelDia();
        GP.crearPistas();
    }


    /* private void iniciarOtrosComponentes() {
        int hora = 9;
        modeloReservaPista1.addRow(new Object[]{"----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------"});
        modeloReservaPista2.addRow(new Object[]{"----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------"});
        modeloReservaPista3.addRow(new Object[]{"----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------", "----------------- " + GA.ahora + " -----------------"});
        for (int i = 0; i < 14; i++) {
            if (hora < 10) {
                horas_inicios[i] = LocalTime.parse("0" + hora + ":00", formatter);
                hora++;
                horas_finales[i] = LocalTime.parse(hora + ":00", formatter);
            } else {
                horas_inicios[i] = LocalTime.parse(hora + ":00", formatter);
                hora++;
                horas_finales[i] = LocalTime.parse(hora + ":00", formatter);
            }
            modeloReservaPista1.addRow(new Object[]{GA.ahora, horas_inicios[i], horas_finales[i]});
            modeloReservaPista2.addRow(new Object[]{GA.ahora, horas_inicios[i], horas_finales[i]});
            modeloReservaPista3.addRow(new Object[]{GA.ahora, horas_inicios[i], horas_finales[i]});
        }
        modeloReservaPista1.addRow(new Object[]{"----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------"});
        modeloReservaPista2.addRow(new Object[]{"----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------"});
        modeloReservaPista3.addRow(new Object[]{"----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------", "----------------- " + GA.tomorrow + " -----------------"});
        for (int i = 0; i < 14; i++) {
            modeloReservaPista1.addRow(new Object[]{GA.tomorrow, horas_inicios[i], horas_finales[i]});
            modeloReservaPista2.addRow(new Object[]{GA.tomorrow, horas_inicios[i], horas_finales[i]});
            modeloReservaPista3.addRow(new Object[]{GA.tomorrow, horas_inicios[i], horas_finales[i]});
        }
        tblReserva.setModel(modeloReservaPista1);
        tblHecha.setModel(modeloHechaPista1);
        rellenarTablas();
    }*/
    private void rellenarTablas() {
        alquileres = GA.gestionListarAlquileres();
        pistas = GP.gestionListarPistas();
        DefaultTableModel modeloReserva;
        DefaultTableModel modeloReservaHecha;
        int hora = 9;
        for (int i = 0; i < pistas.size(); i++) {
            for (int j = 0; j < alquileres.size(); j++) {
                if (alquileres.get(j).p.getNum() == pistas.get(i).getNum()) {
                    modeloReserva = GP.getModeloReserva(pistas.get(i).getNum(), alquileres);
                    modeloReservaHecha = GP.getModeloReservaHecha(pistas.get(i).getNum(), alquileres);

                    tblReserva.setModel(modeloReserva);
                    tblHecha.setModel(modeloReservaHecha);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        jPanel1 = new javax.swing.JPanel();
        btnPista1 = new org.edisoncor.gui.button.ButtonIcon();
        btnPista2 = new org.edisoncor.gui.button.ButtonIcon();
        btnPista3 = new org.edisoncor.gui.button.ButtonIcon();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHecha = new javax.swing.JTable();
        btnFlechaIzq = new org.edisoncor.gui.button.ButtonIcon();
        btnFlechaDch = new org.edisoncor.gui.button.ButtonIcon();
        txtNombre = new javax.swing.JLabel();
        txtTusReservas = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(1360, 762));
        setMinimumSize(new java.awt.Dimension(1360, 762));
        setPreferredSize(new java.awt.Dimension(1360, 762));
        setResizable(false);
        setSize(new java.awt.Dimension(1360, 762));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelHeader1.setText("Reserva tu pista");
        labelHeader1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1360, -1));

        btnPista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista1.setText("buttonIcon1");
        btnPista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista1ActionPerformed(evt);
            }
        });

        btnPista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista2.setText("buttonIcon2");
        btnPista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista2ActionPerformed(evt);
            }
        });

        btnPista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pistaPadelModularVerde.jpg"))); // NOI18N
        btnPista3.setText("buttonIcon3");
        btnPista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPista3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pista 1");

        jLabel2.setText("Pista 2");

        jLabel3.setText("Pista 3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPista1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPista3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPista2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3)))
                .addContainerGap(922, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPista2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPista3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPista1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 90, 1360, 110));

        tblReserva.setBackground(new java.awt.Color(204, 255, 204));
        tblReserva.setForeground(new java.awt.Color(0, 102, 102));
        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora Inicio", "Hora Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReserva.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(tblReserva);
        if (tblReserva.getColumnModel().getColumnCount() > 0) {
            tblReserva.getColumnModel().getColumn(0).setResizable(false);
            tblReserva.getColumnModel().getColumn(1).setResizable(false);
            tblReserva.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 680, 360));

        tblHecha.setBackground(new java.awt.Color(204, 255, 204));
        tblHecha.setForeground(new java.awt.Color(153, 0, 0));
        tblHecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora Inicio", "Hora Final"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHecha.setSelectionForeground(new java.awt.Color(102, 255, 255));
        jScrollPane2.setViewportView(tblHecha);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, 590, 260));

        btnFlechaIzq.setBackground(new java.awt.Color(102, 102, 102));
        btnFlechaIzq.setForeground(new java.awt.Color(102, 102, 102));
        btnFlechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/izquierda.png"))); // NOI18N
        btnFlechaIzq.setText("buttonIcon4");
        btnFlechaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaIzqActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 40, 30));

        btnFlechaDch.setBackground(new java.awt.Color(102, 102, 102));
        btnFlechaDch.setForeground(new java.awt.Color(102, 102, 102));
        btnFlechaDch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/derecha.png"))); // NOI18N
        btnFlechaDch.setText("buttonIcon4");
        btnFlechaDch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlechaDchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlechaDch, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 40, 30));

        txtNombre.setBackground(new java.awt.Color(51, 51, 51));
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setText("Nombre: ");
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, -1, -1));

        txtTusReservas.setBackground(new java.awt.Color(51, 51, 51));
        txtTusReservas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtTusReservas.setForeground(new java.awt.Color(51, 51, 51));
        txtTusReservas.setText("Tus reservas:");
        getContentPane().add(txtTusReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        btnAyuda.setText("Ayuda");
        getContentPane().add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, 70, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1360, 762));
        Fondo.setMinimumSize(new java.awt.Dimension(1360, 762));
        Fondo.setPreferredSize(new java.awt.Dimension(1360, 762));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista1ActionPerformed
        tblReserva.setModel(GP.getModeloReserva(1, alquileres));
        tblHecha.setModel(GP.getModeloReservaHecha(1, alquileres));
    }//GEN-LAST:event_btnPista1ActionPerformed

    private void btnPista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista3ActionPerformed
        tblReserva.setModel(GP.getModeloReserva(3, alquileres));
        tblReserva.setModel(GP.getModeloReservaHecha(3, alquileres));
    }//GEN-LAST:event_btnPista3ActionPerformed

    private void btnPista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPista2ActionPerformed
        tblReserva.setModel(GP.getModeloReserva(2, alquileres));
        tblReserva.setModel(GP.getModeloReservaHecha(2, alquileres));
    }//GEN-LAST:event_btnPista2ActionPerformed

    private void btnFlechaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaIzqActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que quiere borarr la pista a esta hora?", "Alquiler", JOptionPane.YES_NO_OPTION);
        if (resp == 0) {
            DefaultTableModel modelo = (DefaultTableModel) tblReserva.getModel();
            DefaultTableModel modelohecha = (DefaultTableModel) tblHecha.getModel();
            int selec = tblHecha.getSelectedRow();
            modelo.addRow(new Object[]{modelo.getValueAt(selec, 0), modelo.getValueAt(selec, 1), modelo.getValueAt(selec, 2)});
            modelohecha.removeRow(selec);
            //txtNombre.setText("Nombre" + usu.getNombre() + " " + usu.getApellidos());
        }
    }//GEN-LAST:event_btnFlechaIzqActionPerformed

    private void btnFlechaDchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlechaDchActionPerformed

        //int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de que quiere alquilar la pista a esta hora?", "Alquiler", JOptionPane.YES_NO_OPTION);
        //if (resp == 0) {
        DefaultTableModel modelo = (DefaultTableModel) tblReserva.getModel();
        DefaultTableModel modelohecha = (DefaultTableModel) tblHecha.getModel();
        int selec = tblReserva.getSelectedRow();
        modelohecha.addRow(new Object[]{modelo.getValueAt(selec, 0), modelo.getValueAt(selec, 1), modelo.getValueAt(selec, 2)});
        modelo.removeRow(selec);
        //txtNombre.setText("Nombre" + usu.getNombre() + " " + usu.getApellidos());
        //}
    }//GEN-LAST:event_btnFlechaDchActionPerformed

    private void ponLaAyuda() {
        try {
            java.net.URL hsURL = UtilidadesPantalla.obtenerUrlAyuda();
            // Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            // Pone ayuda a item de menu al pulsarlo y a F1 en ventana
            hb.enableHelpOnButton(btnAyuda, "reservar", helpset);
            hb.enableHelpKey(getRootPane(), "reservar", helpset);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservarPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservarPista(new Usuario()).setVisible(true);
            }
        });
    }
    ArrayList<Alquiler> alquileres = new ArrayList<>();
    ArrayList<Pista> pistas = new ArrayList<>();
    GestionPistas GP = new GestionPistas();
    GestionAlquiler GA = new GestionAlquiler();
    Usuario usuarioReservar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btnAyuda;
    private org.edisoncor.gui.button.ButtonIcon btnFlechaDch;
    private org.edisoncor.gui.button.ButtonIcon btnFlechaIzq;
    private org.edisoncor.gui.button.ButtonIcon btnPista1;
    private org.edisoncor.gui.button.ButtonIcon btnPista2;
    private org.edisoncor.gui.button.ButtonIcon btnPista3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    private javax.swing.JTable tblHecha;
    private javax.swing.JTable tblReserva;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTusReservas;
    // End of variables declaration//GEN-END:variables

}
